name: Build Test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew clean build

#workflows 테스트